### ISSUE TITLE
Dynamic clocks close their FD prematurely

### ISSUE THREAD

**Issue by Florob** [pendulum-project/clock-steering#2]
Dynamic clocks use clock IDs based on file descriptors. These are only valid while the file descriptor is actually open, since otherwise the descriptor might be reused for another file.
`UnixClock::open()` immediately drops the opened file, making the created `UnixClock` instantly invalid.
Consequently all calls to `clock_adjtime()` (and similar) return with `EINVAL`.
Additionally clock files have to be opened for reading and writing for `clock_adjtime()` to succeed. Currently they are only opened for reading.

**Comment by Florob** [comment]
The fix for this issue leaks file descriptors. Is that a conscious design choice?

**Comment by folkertdev** [comment]
there is a follow-up PR that keeps track of the file descriptor, so we have the opportunity to not leak the file descriptor. We'll have to play around with this a bit: implementing Drop means the clock cannot be Clone/Copy any more
